# Python NumPy Tutorial freeCodeCamp

NumPy is about arrays 

NumPy 
- no type checking 
- store data next to each other 
- store immages

In [2]:
import numpy as np
import sys

In [4]:
a = np.array([1,2,3], dtype='int32')
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

b.ndim #number of dimentions



2

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize #item size 

4

In [8]:
a.nbytes #whole size

12

# Accesing data

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [10]:
a[1, -2]

np.int64(13)

In [11]:
a[0, :] #rows

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[:,2] #columns

array([ 3, 10])

In [13]:
a[1, 5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [14]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
b[0,1,:]

array([3, 4])

In [16]:
#all 0
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [18]:
#random
np.random.rand(5,2)

array([[0.53978978, 0.8743633 ],
       [0.02108069, 0.88629922],
       [0.02096513, 0.60482635],
       [0.92795802, 0.2664369 ],
       [0.62924695, 0.43432381]])

In [19]:
np.random.randint(5,7,size=(3,3))

array([[5, 5, 5],
       [5, 5, 6],
       [6, 5, 5]])

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr[2, 2] = 9
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
a = np.ones((2,3))
print(a)

b= np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [5]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

In [6]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [9]:
filedata = np.genfromtxt('./data/data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [10]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [11]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])